# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Passbuster' do

pod 'IQKeyboardManager'
pod 'KVNProgress'
pod 'MJExtension'
pod 'FMDB'
pod "JazzHands", "<= 2.0.2"
pod 'CocoaSecurity'
pod 'MJRefresh'

end

target 'PassbusterTests' do

end

target 'PassbusterUITests' do

end

